### ISSUE TITLE
Level navigation

### ISSUE THREAD

**Issue by cdroulers** [cdroulers/block-fly#15]
To navigate within a set of levels. Either going back or entering password for higher levels.

Use localStorage or whatever to save progress by default!

**Comment by olafleur** [comment]
I see two steps in this : 
- [x] Loading a level from a password
- [x] Store the current level in localStorage

Will work on the first one. Should be fairly easy, I guess, because the passwords are already in the levels info.

However, for the moment it's not really "secure" if you only have to peek in the dev console to see the password. What do you think? ;)

**Comment by cdroulers** [comment]
Using the password should be pretty simple button + search in the list of levels for the password. A method on levelSet like `goToLevel(password: string)` should do the trick. Would raise an exception if level not found, which can be caught and an error displayed.

Security is not a concern, since other than doing shitty two-way encryption, which would require the key be present in the JavaScript anyway, there's no way to prevent the users from opening the console and playing around with that stuff. I'm pushing the use of a server for later multi-user features and whatnot, but no need for now.

I'd also use a simple JavaScript `prompt` and no custom popup for the password. Simpler is better and will work well on mobile since it'll be a native control.

For the other part, it's a simple matter of storing the index and having a `goToLevelByIndex(index: number)` method which is called on page load.

**Comment by olafleur** [comment]
Could we close that issue ?
